version: '3'

services:
   mongo:
      image: mongo
      ports:
         - '27017:27017'

   redis:
      image: redis:alpine
      command: redis-server --requirepass RedisPassword
      ports:
         - '6379:6379'

   postgres-dev:
      image: postgres:alpine
      ports:
         - '5432:5432'
      environment:
         POSTGRES_USER: iterations
         POSTGRES_PASSWORD: pass
         POSTGRES_DB: iterations-dev

   postgres-test:
      image: postgres:alpine
      ports:
         - '5433:5432'
      environment:
         POSTGRES_USER: iterations
         POSTGRES_PASSWORD: pass
         POSTGRES_DB: iterations-test

   postgres-prod:
      image: postgres:alpine
      ports:
         - '5434:5432'
      environment:
         POSTGRES_USER: iterations
         POSTGRES_PASSWORD: pass
         POSTGRES_DB: iterations-prod
