version: '3'

services:
   mongo:
      image: mongo
      ports:
         - '27017:27017'

   redis:
      image: redis:alpine
      command: redis-server --requirepass RedisPassword
      ports:
         - '6379:6379'
